### ISSUE TITLE
Fix InfoCmp usage and the Key class

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#10]
Usually, different OS / terminal combination use different key bindings, especially for arrows.  
A simple example:

```
gnodet•~» infocmp xterm | grep khome
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
gnodet•~» infocmp rxvt | grep khome
	khome=\E[7~, kich1=\E[2~, kind=\E[a, kmous=\E[M, knp=\E[6~,
```

This means that if a remote client is using rxvt, the home key won't work because Aesh uses
```
HOME(InfoCmpHelper.getCurrentTranslatedCapabilityAsInts("khome", new int[]{27,79,72})),
```
All the calls to `getCurrentTranslatedCapabilityAsInts` are wrong and will cause problems for remote connections.

**Comment by stalep** [comment]
Yup, this needs to be fixed. What I'm thinking is that we'll use the Connection.terminalType() to fetch the correct and based on that get the correct mappings.

**Comment by gnodet** [comment]
Yes, that's how it should be done.  Though be aware that the implementation of `TerminalConnection.terminalType()` is wrong.  It should return `terminal.getType()` instead of `terminal.getName()`.

**Comment by stalep** [comment]
ah, thanks. ill fix that!

**Comment by stalep** [comment]
this should now be fixed in master

**Comment by gnodet** [comment]
I've seen you changed to 0.16-SNAPSHOT.
Have you deployed a 0.15 release somewhere ? It's not in http://repository.jboss.org/org/jboss/aesh/aesh-readline/
