### ISSUE TITLE
The terminal should be responsible for echoing signal if needed

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#11]
This was the case previously.  It has changed recently.
This is controled by the `Attributes.LocalFlag.ECHOCTL` attribute on real terminals.  Terminal emulations should follow this flag.

**Comment by gnodet** [comment]
See the following code:
https://github.com/aeshell/aesh-readline/blob/master/readline/src/main/java/org/aesh/readline/Readline.java#L267-L274

**Comment by stalep** [comment]
The reason we have that code in Readline is because some edit modes might have a state (search mode) and it needs to behave properly when receiving eg ctrl-c.

**Comment by gnodet** [comment]
The problem in the code I was pointing is not the handling of the INT signal, it's the fact that `Readline` is printing `^C` on the terminal.
In my case, I always end up with `^C^C`, one because of the terminal, which is expected given its attributes, and the other one by readline.

**Comment by stalep** [comment]
I see, what do jline do when the user is doing a search and presses ctrl-c? 
In bash it exits the search and do not print "^C".

**Comment by gnodet** [comment]
In JLine, the interrupt signal exists the readline() call, in both editing or search mode (similar to bash or zsh).  Usually, this is done in a loop, so that the prompt is displayed again and a new line read.
Note that in both bash and zsh, ^C is not printed.  That's because the terminal is in raw mode and the echo flag is not set.  JLine has the same behavior.

Here's how the real terminal react:
```
gnodet•~» stty -echo echoctl ; sleep 100 ; stty sane

gnodet•~» stty echo echoctl ; sleep 100 ; stty sane
foo^C
gnodet•~» stty echo -echoctl ; sleep 100 ; stty sane
foo
```
In the three cases above, I entered `foo<^C>`.

Anyway, if you want readline to print ^C, I'm fine with that, but it should happen only when reading a line and not when executing a command.  When executing command, the usual unix terminal behavior should be used imho.

**Comment by stalep** [comment]
readline will now check the ECHOCTL flag before writing out ^C. this should be fixed in the latest commit in master.
