### ISSUE TITLE
Investigate using String instead of int[]

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#13]
That would make things much easier to use, to debug, with no real performance issues, as 4 bytes chars are really rare.  Actually, it would be a small memory improvement.

**Comment by gnodet** [comment]
See https://github.com/aeshell/aesh-readline/blob/master/terminal-api/src/main/java/org/aesh/terminal/Connection.java#L150-L154

**Comment by stalep** [comment]
Internally the input is int[] and we've seen that this reduces memory usage overall.
In the case of that method, yes there is an overhead, but since the output still needs to be transformed with the correct charset the overhead is fairly minimal.

**Comment by gnodet** [comment]
Internally, that's an implementation detail.
But the `Connection` interface is using `int[]` for `stdinHandler` and `stdoutHandler`, so that's not really internal anymore.
If you don't want to use `String` for performance reasons, what about using `CharSequence` which gives all the room to implement something both user friendly and fast.

**Comment by stalep** [comment]
Connection is not really meant as a public api in the sense that anyone using æsh-readline would implement it. Connection is usually built for you (similar to Terminal in jline). Usually Decoder/Encoder can be reused for all implementations of Connection, but it makes sense to leave them open for change.
Connection also has a .write(String) method that can be used if needed.
The Completion api is using String for ease of use, so the user interaction is all strings afaik.
