### ISSUE TITLE
The default mode for the terminal should be the canonical mode

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#17]
The raw mode should only be used "locally" and should not be the default mode.
The raw mode should be entered when the line reading process is started and exited when the line has been read and will be given to the request handler (or the readline method is exited with an exception).

**Comment by stalep** [comment]
I'm not against this, I just want to understand the reason to do this?
This will usually cause æsh to set/reset the tty settings very often, what is the benefit of this?

**Comment by gnodet** [comment]
It's more in line with what a unix system does with the terminal.  Commands that require the terminal to be in raw mode are not usual: it includes things like the less pager, an ssh client, full size applications.  Other usual commands just expect the terminal to be in the canonical mode.  If you don't, the command won't be able to use `System.in` in the usual way for example.

**Comment by stalep** [comment]
I understand your reasoning behind this. It makes it a bit "harder" for developers to write commands though, but i understand why. I need to think about this a bit.
