### ISSUE TITLE
Support for ^D is broken

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#18]
The `ShellExample` can not be exited using `Ctrl+D`, but this is not specific to this example.

**Comment by gnodet** [comment]
I managed to bypass the problem my implementing my own `TerminalConnection`.

**Comment by stalep** [comment]
ShellExample does quit when pressing Ctrl-D (atleast locally), was there a specific situation it doesn't exit?
ShellExample just quit on any signal passed to the Signalhandler.

**Comment by gnodet** [comment]
MMh, this might have been a broken terminal...
