### ISSUE TITLE
The TerminalConnection should restore signal handlers to their previous values

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#21]
The terminal connection sets some signal handlers, but should restore them to their previous values when the connection is closed.
  https://github.com/aeshell/aesh-readline/blob/master/readline/src/main/java/org/aesh/readline/tty/terminal/TerminalConnection.java#L85-L99

**Comment by stalep** [comment]
I dont quite understand what you mean. TerminalConnection only subscribe to certain Signals afaik?

**Comment by gnodet** [comment]
The call to `terminal.handle()` returns the previously registered `SignalHandler`.
I think it would be better if the `TerminalConnection#close()` method would restore those previous values.
