### ISSUE TITLE
putty / END key support

### ISSUE THREAD

**Issue by davidklika** [aeshell/aesh-readline#49]
According to the putty documentation (https://www.ssh.com/ssh/putty/putty-manuals/0.68/Chapter4.html section 4.4.2 HOME and END keys invoke these character sequences:
for xterm: ESC [1~ and ESC [4~ 
for rxvt: ESC [H and ESC [Ow
JLine process correctly only HOME key in rxvt putty mode, the other character sequences are printed on the terminal instead of changing cursor position.
Thank you, David

**Comment by stalep** [comment]
This should be fixed in master and the next release. Thanks for reporting!
